//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1fg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int clientid { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
