//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1fg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invent
    {
        public int InventID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
    }
}
