//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1fg
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrdersItem = new HashSet<OrdersItem>();
        }
    
        public int orderid { get; set; }
        public Nullable<int> clientid { get; set; }
        public string order_date { get; set; }
        public string status { get; set; }
        public Nullable<int> total_price { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<OrdersItem> OrdersItem { get; set; }
    }
}
