//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1fg
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersItem
    {
        public int id { get; set; }
        public Nullable<int> orderid { get; set; }
        public Nullable<int> productsid { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
